title: My blog
description: "Welcome to my Blog. I write notes, mini notes and more!"
#baseurl: ""
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  C0DE33301

# Build settings
header_pages:
  - index.md
  - notes.md
  - ctfs.md
  - about.md
  - contact.md

style: hacker

footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  notes:
    output: true
    permalink: /notes/:path/
  ctfs:
    output: true
    permalink: /ctfs/:path/